# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\anafa\OneDrive\Desktop\SocketsProgramingProject\diwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 599)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color:hsl(210, 36%, 96%);;\n"
"display: flex;\n"
"flex-direction: column;\n"
"align-items: center;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 0, 451, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.showPortandIpaddress = QtWidgets.QPushButton(self.frame)
        self.showPortandIpaddress.setGeometry(QtCore.QRect(210, 440, 231, 41))
        self.showPortandIpaddress.setStyleSheet("border-radius:20px;\n"
"background-color: hsl(205, 78%, 60%);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.showPortandIpaddress.setObjectName("showPortandIpaddress")
        self.message = QtWidgets.QTextEdit(self.frame)
        self.message.setGeometry(QtCore.QRect(100, 340, 280, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message.setFont(font)
        self.message.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.message.setToolTipDuration(0)
        self.message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.message.setAutoFillBackground(False)
        self.message.setStyleSheet("  height: 3rem;\n"
"  width: 95%;\n"
"  box-sizing: border-box;\n"
"  font-size: 1.5rem;\n"
"  color: hsl(205, 78%, 60%);\n"
"  padding: 0.25rem 0.5rem;\n"
"  text-transform: capitalize;\n"
"\n"
"  transition: all 0.3s linear;\n"
"  cursor: pointer;")
        self.message.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.message.setFrameShadow(QtWidgets.QFrame.Plain)
        self.message.setLineWidth(12)
        self.message.setMidLineWidth(0)
        self.message.setObjectName("message")
        self.sendMsg = QtWidgets.QPushButton(self.frame)
        self.sendMsg.setGeometry(QtCore.QRect(120, 390, 241, 41))
        self.sendMsg.setStyleSheet("border-radius:20px;\n"
"background-color: hsl(205, 78%, 60%);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.sendMsg.setObjectName("sendMsg")
        self.status = QtWidgets.QLabel(self.frame)
        self.status.setGeometry(QtCore.QRect(40, 10, 71, 16))
        self.status.setObjectName("status")
        self.goBack = QtWidgets.QPushButton(self.frame)
        self.goBack.setGeometry(QtCore.QRect(160, 490, 151, 41))
        self.goBack.setStyleSheet("border-radius:20px;\n"
"background-color: hsl(205, 78%, 60%);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.goBack.setObjectName("goBack")
        self.dialog = QtWidgets.QTextBrowser(self.frame)
        self.dialog.setGeometry(QtCore.QRect(100, 51, 281, 261))
        self.dialog.setObjectName("dialog")
        self.connect = QtWidgets.QPushButton(self.frame)
        self.connect.setGeometry(QtCore.QRect(50, 440, 151, 41))
        self.connect.setStyleSheet("border-radius:20px;\n"
"background-color: hsl(205, 78%, 60%);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.connect.setObjectName("connect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPort_Number = QtWidgets.QAction(MainWindow)
        self.actionPort_Number.setObjectName("actionPort_Number")
        self.actionIP_Address = QtWidgets.QAction(MainWindow)
        self.actionIP_Address.setObjectName("actionIP_Address")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showPortandIpaddress.setText(_translate("MainWindow", "Show My Port and IP"))
        self.sendMsg.setText(_translate("MainWindow", "Send"))
        self.status.setText(_translate("MainWindow", "Connected"))
        self.goBack.setText(_translate("MainWindow", "Back"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.actionPort_Number.setText(_translate("MainWindow", "Port Number"))
        self.actionIP_Address.setText(_translate("MainWindow", "IP Address"))
