# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\anafa\OneDrive\Desktop\SocketsProgramingProject\portWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 624)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color:hsl(210, 36%, 96%);;\n"
"display: flex;\n"
"flex-direction: column;\n"
"align-items: center;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 120, 400, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.portNumber = QtWidgets.QTextEdit(self.frame)
        self.portNumber.setGeometry(QtCore.QRect(60, 70, 280, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.portNumber.setFont(font)
        self.portNumber.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.portNumber.setToolTipDuration(0)
        self.portNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.portNumber.setAutoFillBackground(False)
        self.portNumber.setStyleSheet("  height: 3rem;\n"
"  width: 95%;\n"
"  box-sizing: border-box;\n"
"  font-size: 1.5rem;\n"
"  color: hsl(205, 78%, 60%);\n"
"  padding: 0.25rem 0.5rem;\n"
"  text-transform: capitalize;\n"
"\n"
"  transition: all 0.3s linear;\n"
"  cursor: pointer;")
        self.portNumber.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.portNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.portNumber.setLineWidth(12)
        self.portNumber.setMidLineWidth(0)
        self.portNumber.setObjectName("portNumber")
        self.setPort = QtWidgets.QPushButton(self.frame)
        self.setPort.setGeometry(QtCore.QRect(80, 170, 220, 50))
        self.setPort.setStyleSheet("border-radius:20px;\n"
"background-color: hsl(205, 78%, 60%);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.setPort.setObjectName("setPort")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.unAcceptePort = QtWidgets.QLabel(self.frame)
        self.unAcceptePort.setGeometry(QtCore.QRect(60, 130, 181, 21))
        self.unAcceptePort.setObjectName("unAcceptePort")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPort_Number = QtWidgets.QAction(MainWindow)
        self.actionPort_Number.setObjectName("actionPort_Number")
        self.actionIP_Address = QtWidgets.QAction(MainWindow)
        self.actionIP_Address.setObjectName("actionIP_Address")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.setPort.setText(_translate("MainWindow", "Set Port"))
        self.label.setText(_translate("MainWindow", "Enter Port Number:"))
        self.unAcceptePort.setText(_translate("MainWindow", "Not Accepted Port Number"))
        self.actionPort_Number.setText(_translate("MainWindow", "Port Number"))
        self.actionIP_Address.setText(_translate("MainWindow", "IP Address"))
